name: mk-docs 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip3 install mkdocs-material 
      - run: pip3 install mkdocs-macros-plugin
      - run: pip3 install pymdown-extensions
      # - run: pip install mkdocs-mermaid2-plugin
      # - run: pip3 install mdx_gh_links
      # - run: pip install mkdocs-with-pdf
      - run: mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
